[workspace]
members = [
]
[package]
name = "namida"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
libc= "0.2"
md5 = "0.7.0"
rand = "0.8.5"
